id: P001796
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN542
  title: ཤེར་ཕྱིན་སྒོམ་རིམ་དང་སྨྱུང་གནས་ཕན་ཡོན།
  author: ''
  volumes:
    30a09a69d4bc46618ded48ffab5866d3:
      image_group_id: I3CN3786
      title: ''
      volume_number: 1
      total_pages: 338
      base_file: v001.txt
