id: I1AC9C39F
legacy_id: P001796
ocr_import_info:
  bdrc_scan_id: W3CN542
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T21:57:52'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T12:12:12.785079+00:00'
last_modified: 2022-08-27 20:12:32.452194
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN542
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW3CN542
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཤེར་ཕྱིན་སྒོམ་རིམ་དང་སྨྱུང་གནས་ཕན་ཡོན།
statistics:
  ocr_word_mean_confidence_index: 0.9061916576690747
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I3CN3786:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3786
      total_pages: 338
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN3786.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9061916576690747
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
